//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMachine.TreolanProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/", ConfigurationName="TreolanProductService.B2BWebServiceSoap")]
    public interface B2BWebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем Login из пространства имен https://b2b.treolan.ru/Webservice2008/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/ProductInfo", ReplyAction="*")]
        PriceMachine.TreolanProductService.ProductInfoResponse ProductInfo(PriceMachine.TreolanProductService.ProductInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/ProductInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.ProductInfoResponse> ProductInfoAsync(PriceMachine.TreolanProductService.ProductInfoRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Login из пространства имен https://b2b.treolan.ru/Webservice2008/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/ProductInfoV2", ReplyAction="*")]
        PriceMachine.TreolanProductService.ProductInfoV2Response ProductInfoV2(PriceMachine.TreolanProductService.ProductInfoV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/ProductInfoV2", ReplyAction="*")]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.ProductInfoV2Response> ProductInfoV2Async(PriceMachine.TreolanProductService.ProductInfoV2Request request);
        
        // CODEGEN: Контракт генерации сообщений с именем Login из пространства имен https://b2b.treolan.ru/Webservice2008/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/GetCargoList", ReplyAction="*")]
        PriceMachine.TreolanProductService.GetCargoListResponse GetCargoList(PriceMachine.TreolanProductService.GetCargoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/GetCargoList", ReplyAction="*")]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetCargoListResponse> GetCargoListAsync(PriceMachine.TreolanProductService.GetCargoListRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Login из пространства имен https://b2b.treolan.ru/Webservice2008/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/GetCargoByNumb", ReplyAction="*")]
        PriceMachine.TreolanProductService.GetCargoByNumbResponse GetCargoByNumb(PriceMachine.TreolanProductService.GetCargoByNumbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/GetCargoByNumb", ReplyAction="*")]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetCargoByNumbResponse> GetCargoByNumbAsync(PriceMachine.TreolanProductService.GetCargoByNumbRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Login из пространства имен https://b2b.treolan.ru/Webservice2008/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/GetSchet", ReplyAction="*")]
        PriceMachine.TreolanProductService.GetSchetResponse GetSchet(PriceMachine.TreolanProductService.GetSchetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/GetSchet", ReplyAction="*")]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetSchetResponse> GetSchetAsync(PriceMachine.TreolanProductService.GetSchetRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Login из пространства имен https://b2b.treolan.ru/Webservice2008/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/DeleteSchetPosition", ReplyAction="*")]
        PriceMachine.TreolanProductService.DeleteSchetPositionResponse DeleteSchetPosition(PriceMachine.TreolanProductService.DeleteSchetPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/DeleteSchetPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.DeleteSchetPositionResponse> DeleteSchetPositionAsync(PriceMachine.TreolanProductService.DeleteSchetPositionRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Login из пространства имен https://b2b.treolan.ru/Webservice2008/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/MoveSchet", ReplyAction="*")]
        PriceMachine.TreolanProductService.MoveSchetResponse MoveSchet(PriceMachine.TreolanProductService.MoveSchetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://b2b.treolan.ru/Webservice2008/MoveSchet", ReplyAction="*")]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.MoveSchetResponse> MoveSchetAsync(PriceMachine.TreolanProductService.MoveSchetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductInfo", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.ProductInfoRequestBody Body;
        
        public ProductInfoRequest() {
        }
        
        public ProductInfoRequest(PriceMachine.TreolanProductService.ProductInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class ProductInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Articul;
        
        public ProductInfoRequestBody() {
        }
        
        public ProductInfoRequestBody(string Login, string password, string Articul) {
            this.Login = Login;
            this.password = password;
            this.Articul = Articul;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductInfoResponse", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.ProductInfoResponseBody Body;
        
        public ProductInfoResponse() {
        }
        
        public ProductInfoResponse(PriceMachine.TreolanProductService.ProductInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class ProductInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ProductInfoResult;
        
        public ProductInfoResponseBody() {
        }
        
        public ProductInfoResponseBody(System.Xml.Linq.XElement ProductInfoResult) {
            this.ProductInfoResult = ProductInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductInfoV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductInfoV2", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.ProductInfoV2RequestBody Body;
        
        public ProductInfoV2Request() {
        }
        
        public ProductInfoV2Request(PriceMachine.TreolanProductService.ProductInfoV2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class ProductInfoV2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Articul;
        
        public ProductInfoV2RequestBody() {
        }
        
        public ProductInfoV2RequestBody(string Login, string password, string Articul) {
            this.Login = Login;
            this.password = password;
            this.Articul = Articul;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductInfoV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductInfoV2Response", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.ProductInfoV2ResponseBody Body;
        
        public ProductInfoV2Response() {
        }
        
        public ProductInfoV2Response(PriceMachine.TreolanProductService.ProductInfoV2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class ProductInfoV2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ProductInfoV2Result;
        
        public ProductInfoV2ResponseBody() {
        }
        
        public ProductInfoV2ResponseBody(System.Xml.Linq.XElement ProductInfoV2Result) {
            this.ProductInfoV2Result = ProductInfoV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCargoListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCargoList", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.GetCargoListRequestBody Body;
        
        public GetCargoListRequest() {
        }
        
        public GetCargoListRequest(PriceMachine.TreolanProductService.GetCargoListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class GetCargoListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DateBeg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DateEnd;
        
        public GetCargoListRequestBody() {
        }
        
        public GetCargoListRequestBody(string Login, string password, string DateBeg, string DateEnd) {
            this.Login = Login;
            this.password = password;
            this.DateBeg = DateBeg;
            this.DateEnd = DateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCargoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCargoListResponse", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.GetCargoListResponseBody Body;
        
        public GetCargoListResponse() {
        }
        
        public GetCargoListResponse(PriceMachine.TreolanProductService.GetCargoListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class GetCargoListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCargoListResult;
        
        public GetCargoListResponseBody() {
        }
        
        public GetCargoListResponseBody(System.Xml.Linq.XElement GetCargoListResult) {
            this.GetCargoListResult = GetCargoListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCargoByNumbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCargoByNumb", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.GetCargoByNumbRequestBody Body;
        
        public GetCargoByNumbRequest() {
        }
        
        public GetCargoByNumbRequest(PriceMachine.TreolanProductService.GetCargoByNumbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class GetCargoByNumbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long CargoNumb;
        
        public GetCargoByNumbRequestBody() {
        }
        
        public GetCargoByNumbRequestBody(string Login, string password, long CargoNumb) {
            this.Login = Login;
            this.password = password;
            this.CargoNumb = CargoNumb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCargoByNumbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCargoByNumbResponse", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.GetCargoByNumbResponseBody Body;
        
        public GetCargoByNumbResponse() {
        }
        
        public GetCargoByNumbResponse(PriceMachine.TreolanProductService.GetCargoByNumbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class GetCargoByNumbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCargoByNumbResult;
        
        public GetCargoByNumbResponseBody() {
        }
        
        public GetCargoByNumbResponseBody(System.Xml.Linq.XElement GetCargoByNumbResult) {
            this.GetCargoByNumbResult = GetCargoByNumbResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchet", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.GetSchetRequestBody Body;
        
        public GetSchetRequest() {
        }
        
        public GetSchetRequest(PriceMachine.TreolanProductService.GetSchetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class GetSchetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SchetName;
        
        public GetSchetRequestBody() {
        }
        
        public GetSchetRequestBody(string Login, string password, string SchetName) {
            this.Login = Login;
            this.password = password;
            this.SchetName = SchetName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchetResponse", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.GetSchetResponseBody Body;
        
        public GetSchetResponse() {
        }
        
        public GetSchetResponse(PriceMachine.TreolanProductService.GetSchetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class GetSchetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetSchetResult;
        
        public GetSchetResponseBody() {
        }
        
        public GetSchetResponseBody(System.Xml.Linq.XElement GetSchetResult) {
            this.GetSchetResult = GetSchetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSchetPositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSchetPosition", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.DeleteSchetPositionRequestBody Body;
        
        public DeleteSchetPositionRequest() {
        }
        
        public DeleteSchetPositionRequest(PriceMachine.TreolanProductService.DeleteSchetPositionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class DeleteSchetPositionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLQuery;
        
        public DeleteSchetPositionRequestBody() {
        }
        
        public DeleteSchetPositionRequestBody(string Login, string password, string XMLQuery) {
            this.Login = Login;
            this.password = password;
            this.XMLQuery = XMLQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSchetPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSchetPositionResponse", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.DeleteSchetPositionResponseBody Body;
        
        public DeleteSchetPositionResponse() {
        }
        
        public DeleteSchetPositionResponse(PriceMachine.TreolanProductService.DeleteSchetPositionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class DeleteSchetPositionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteSchetPositionResult;
        
        public DeleteSchetPositionResponseBody() {
        }
        
        public DeleteSchetPositionResponseBody(System.Xml.Linq.XElement DeleteSchetPositionResult) {
            this.DeleteSchetPositionResult = DeleteSchetPositionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveSchetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveSchet", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.MoveSchetRequestBody Body;
        
        public MoveSchetRequest() {
        }
        
        public MoveSchetRequest(PriceMachine.TreolanProductService.MoveSchetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class MoveSchetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLQuery;
        
        public MoveSchetRequestBody() {
        }
        
        public MoveSchetRequestBody(string Login, string password, string XMLQuery) {
            this.Login = Login;
            this.password = password;
            this.XMLQuery = XMLQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveSchetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveSchetResponse", Namespace="https://b2b.treolan.ru/Webservice2008/", Order=0)]
        public PriceMachine.TreolanProductService.MoveSchetResponseBody Body;
        
        public MoveSchetResponse() {
        }
        
        public MoveSchetResponse(PriceMachine.TreolanProductService.MoveSchetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://b2b.treolan.ru/Webservice2008/")]
    public partial class MoveSchetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement MoveSchetResult;
        
        public MoveSchetResponseBody() {
        }
        
        public MoveSchetResponseBody(System.Xml.Linq.XElement MoveSchetResult) {
            this.MoveSchetResult = MoveSchetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface B2BWebServiceSoapChannel : PriceMachine.TreolanProductService.B2BWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B2BWebServiceSoapClient : System.ServiceModel.ClientBase<PriceMachine.TreolanProductService.B2BWebServiceSoap>, PriceMachine.TreolanProductService.B2BWebServiceSoap {
        
        public B2BWebServiceSoapClient() {
        }
        
        public B2BWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B2BWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceMachine.TreolanProductService.ProductInfoResponse PriceMachine.TreolanProductService.B2BWebServiceSoap.ProductInfo(PriceMachine.TreolanProductService.ProductInfoRequest request) {
            return base.Channel.ProductInfo(request);
        }
        
        public System.Xml.Linq.XElement ProductInfo(string Login, string password, string Articul) {
            PriceMachine.TreolanProductService.ProductInfoRequest inValue = new PriceMachine.TreolanProductService.ProductInfoRequest();
            inValue.Body = new PriceMachine.TreolanProductService.ProductInfoRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.Articul = Articul;
            PriceMachine.TreolanProductService.ProductInfoResponse retVal = ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).ProductInfo(inValue);
            return retVal.Body.ProductInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.ProductInfoResponse> PriceMachine.TreolanProductService.B2BWebServiceSoap.ProductInfoAsync(PriceMachine.TreolanProductService.ProductInfoRequest request) {
            return base.Channel.ProductInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PriceMachine.TreolanProductService.ProductInfoResponse> ProductInfoAsync(string Login, string password, string Articul) {
            PriceMachine.TreolanProductService.ProductInfoRequest inValue = new PriceMachine.TreolanProductService.ProductInfoRequest();
            inValue.Body = new PriceMachine.TreolanProductService.ProductInfoRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.Articul = Articul;
            return ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).ProductInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceMachine.TreolanProductService.ProductInfoV2Response PriceMachine.TreolanProductService.B2BWebServiceSoap.ProductInfoV2(PriceMachine.TreolanProductService.ProductInfoV2Request request) {
            return base.Channel.ProductInfoV2(request);
        }
        
        public System.Xml.Linq.XElement ProductInfoV2(string Login, string password, string Articul) {
            PriceMachine.TreolanProductService.ProductInfoV2Request inValue = new PriceMachine.TreolanProductService.ProductInfoV2Request();
            inValue.Body = new PriceMachine.TreolanProductService.ProductInfoV2RequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.Articul = Articul;
            PriceMachine.TreolanProductService.ProductInfoV2Response retVal = ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).ProductInfoV2(inValue);
            return retVal.Body.ProductInfoV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.ProductInfoV2Response> PriceMachine.TreolanProductService.B2BWebServiceSoap.ProductInfoV2Async(PriceMachine.TreolanProductService.ProductInfoV2Request request) {
            return base.Channel.ProductInfoV2Async(request);
        }
        
        public System.Threading.Tasks.Task<PriceMachine.TreolanProductService.ProductInfoV2Response> ProductInfoV2Async(string Login, string password, string Articul) {
            PriceMachine.TreolanProductService.ProductInfoV2Request inValue = new PriceMachine.TreolanProductService.ProductInfoV2Request();
            inValue.Body = new PriceMachine.TreolanProductService.ProductInfoV2RequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.Articul = Articul;
            return ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).ProductInfoV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceMachine.TreolanProductService.GetCargoListResponse PriceMachine.TreolanProductService.B2BWebServiceSoap.GetCargoList(PriceMachine.TreolanProductService.GetCargoListRequest request) {
            return base.Channel.GetCargoList(request);
        }
        
        public System.Xml.Linq.XElement GetCargoList(string Login, string password, string DateBeg, string DateEnd) {
            PriceMachine.TreolanProductService.GetCargoListRequest inValue = new PriceMachine.TreolanProductService.GetCargoListRequest();
            inValue.Body = new PriceMachine.TreolanProductService.GetCargoListRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.DateBeg = DateBeg;
            inValue.Body.DateEnd = DateEnd;
            PriceMachine.TreolanProductService.GetCargoListResponse retVal = ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).GetCargoList(inValue);
            return retVal.Body.GetCargoListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetCargoListResponse> PriceMachine.TreolanProductService.B2BWebServiceSoap.GetCargoListAsync(PriceMachine.TreolanProductService.GetCargoListRequest request) {
            return base.Channel.GetCargoListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetCargoListResponse> GetCargoListAsync(string Login, string password, string DateBeg, string DateEnd) {
            PriceMachine.TreolanProductService.GetCargoListRequest inValue = new PriceMachine.TreolanProductService.GetCargoListRequest();
            inValue.Body = new PriceMachine.TreolanProductService.GetCargoListRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.DateBeg = DateBeg;
            inValue.Body.DateEnd = DateEnd;
            return ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).GetCargoListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceMachine.TreolanProductService.GetCargoByNumbResponse PriceMachine.TreolanProductService.B2BWebServiceSoap.GetCargoByNumb(PriceMachine.TreolanProductService.GetCargoByNumbRequest request) {
            return base.Channel.GetCargoByNumb(request);
        }
        
        public System.Xml.Linq.XElement GetCargoByNumb(string Login, string password, long CargoNumb) {
            PriceMachine.TreolanProductService.GetCargoByNumbRequest inValue = new PriceMachine.TreolanProductService.GetCargoByNumbRequest();
            inValue.Body = new PriceMachine.TreolanProductService.GetCargoByNumbRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.CargoNumb = CargoNumb;
            PriceMachine.TreolanProductService.GetCargoByNumbResponse retVal = ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).GetCargoByNumb(inValue);
            return retVal.Body.GetCargoByNumbResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetCargoByNumbResponse> PriceMachine.TreolanProductService.B2BWebServiceSoap.GetCargoByNumbAsync(PriceMachine.TreolanProductService.GetCargoByNumbRequest request) {
            return base.Channel.GetCargoByNumbAsync(request);
        }
        
        public System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetCargoByNumbResponse> GetCargoByNumbAsync(string Login, string password, long CargoNumb) {
            PriceMachine.TreolanProductService.GetCargoByNumbRequest inValue = new PriceMachine.TreolanProductService.GetCargoByNumbRequest();
            inValue.Body = new PriceMachine.TreolanProductService.GetCargoByNumbRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.CargoNumb = CargoNumb;
            return ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).GetCargoByNumbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceMachine.TreolanProductService.GetSchetResponse PriceMachine.TreolanProductService.B2BWebServiceSoap.GetSchet(PriceMachine.TreolanProductService.GetSchetRequest request) {
            return base.Channel.GetSchet(request);
        }
        
        public System.Xml.Linq.XElement GetSchet(string Login, string password, string SchetName) {
            PriceMachine.TreolanProductService.GetSchetRequest inValue = new PriceMachine.TreolanProductService.GetSchetRequest();
            inValue.Body = new PriceMachine.TreolanProductService.GetSchetRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.SchetName = SchetName;
            PriceMachine.TreolanProductService.GetSchetResponse retVal = ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).GetSchet(inValue);
            return retVal.Body.GetSchetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetSchetResponse> PriceMachine.TreolanProductService.B2BWebServiceSoap.GetSchetAsync(PriceMachine.TreolanProductService.GetSchetRequest request) {
            return base.Channel.GetSchetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PriceMachine.TreolanProductService.GetSchetResponse> GetSchetAsync(string Login, string password, string SchetName) {
            PriceMachine.TreolanProductService.GetSchetRequest inValue = new PriceMachine.TreolanProductService.GetSchetRequest();
            inValue.Body = new PriceMachine.TreolanProductService.GetSchetRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.SchetName = SchetName;
            return ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).GetSchetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceMachine.TreolanProductService.DeleteSchetPositionResponse PriceMachine.TreolanProductService.B2BWebServiceSoap.DeleteSchetPosition(PriceMachine.TreolanProductService.DeleteSchetPositionRequest request) {
            return base.Channel.DeleteSchetPosition(request);
        }
        
        public System.Xml.Linq.XElement DeleteSchetPosition(string Login, string password, string XMLQuery) {
            PriceMachine.TreolanProductService.DeleteSchetPositionRequest inValue = new PriceMachine.TreolanProductService.DeleteSchetPositionRequest();
            inValue.Body = new PriceMachine.TreolanProductService.DeleteSchetPositionRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.XMLQuery = XMLQuery;
            PriceMachine.TreolanProductService.DeleteSchetPositionResponse retVal = ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).DeleteSchetPosition(inValue);
            return retVal.Body.DeleteSchetPositionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.DeleteSchetPositionResponse> PriceMachine.TreolanProductService.B2BWebServiceSoap.DeleteSchetPositionAsync(PriceMachine.TreolanProductService.DeleteSchetPositionRequest request) {
            return base.Channel.DeleteSchetPositionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PriceMachine.TreolanProductService.DeleteSchetPositionResponse> DeleteSchetPositionAsync(string Login, string password, string XMLQuery) {
            PriceMachine.TreolanProductService.DeleteSchetPositionRequest inValue = new PriceMachine.TreolanProductService.DeleteSchetPositionRequest();
            inValue.Body = new PriceMachine.TreolanProductService.DeleteSchetPositionRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.XMLQuery = XMLQuery;
            return ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).DeleteSchetPositionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PriceMachine.TreolanProductService.MoveSchetResponse PriceMachine.TreolanProductService.B2BWebServiceSoap.MoveSchet(PriceMachine.TreolanProductService.MoveSchetRequest request) {
            return base.Channel.MoveSchet(request);
        }
        
        public System.Xml.Linq.XElement MoveSchet(string Login, string password, string XMLQuery) {
            PriceMachine.TreolanProductService.MoveSchetRequest inValue = new PriceMachine.TreolanProductService.MoveSchetRequest();
            inValue.Body = new PriceMachine.TreolanProductService.MoveSchetRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.XMLQuery = XMLQuery;
            PriceMachine.TreolanProductService.MoveSchetResponse retVal = ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).MoveSchet(inValue);
            return retVal.Body.MoveSchetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PriceMachine.TreolanProductService.MoveSchetResponse> PriceMachine.TreolanProductService.B2BWebServiceSoap.MoveSchetAsync(PriceMachine.TreolanProductService.MoveSchetRequest request) {
            return base.Channel.MoveSchetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PriceMachine.TreolanProductService.MoveSchetResponse> MoveSchetAsync(string Login, string password, string XMLQuery) {
            PriceMachine.TreolanProductService.MoveSchetRequest inValue = new PriceMachine.TreolanProductService.MoveSchetRequest();
            inValue.Body = new PriceMachine.TreolanProductService.MoveSchetRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.password = password;
            inValue.Body.XMLQuery = XMLQuery;
            return ((PriceMachine.TreolanProductService.B2BWebServiceSoap)(this)).MoveSchetAsync(inValue);
        }
    }
}
